apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-sjm-tpa-python14
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-sjm-tpa-python14 
  name: test-sjm-tpa-python14
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: test-sjm-tpa-python14 
